### ISSUE TITLE
Since updating to 1.3.1 I get the following error.   Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by laplacacm** [rewardone/homeassistant-culligan-water-softener#8]
2024-01-05 08:27:45.550 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/culligan/sensor.py", line 387, in state
    elif bypass in (True,1,2,3,4,5,6) or bypass_time > 0:
                                         ^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by laplacacm** [comment]
I apologize, this is not a new error.  This seems to be the same as before.   Am I getting this because of the Reverse Osmosis devices?   Is there a way to turn those off?   I already disabled all of those entities.

**Comment by laplacacm** [comment]
Now, the integration won't load at all.   "Failed to Set up"   I am now getting this error: 

    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/culligan/__init__.py", line 124, in async_setup_entry
    supported_devices += device
TypeError: 'Softener' object is not iterable

**Comment by rewardone** [comment]
How about 1.3.2-beta2?

**Comment by laplacacm** [comment]
for 1.3.2-beta2 it still is failing to set up.   This is the error now: 

2024-01-06 16:20:45.559 ERROR (MainThread) [custom_components.culligan] Unexpected error updating Culligan devices
Traceback (most recent call last):
  File "/config/custom_components/culligan/update_coordinator.py", line 213, in _async_update_data
    return await asyncio.gather(
                 ^^^^^^^^^^^^^^^
  File "/config/custom_components/culligan/update_coordinator.py", line 214, in 
    *(self._async_update_softener(v) for v in online_devices)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/culligan/update_coordinator.py", line 210, in 
    online_devices = (self.culligan_devices[dsn] for dsn in self._online_dsns)
                      ~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'AC000W004589104'

**Comment by rewardone** [comment]
Ah, even though the coordinator was only passed supported devices, it checks the API for all online devices. It saw the unsupported devices as online, but we didn't pass them to the coordinator, hence the key error. 

I've added a check to only refresh the online and supported devices. Please try 1.3.2 beta 3.

**Comment by laplacacm** [comment]
Beta 3 is working flawlessly!   No errors at all!  Thank you!

**Comment by rewardone** [comment]
1.3.2 release marked as latest
